# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  #only:
  #  - master
  tags:
    - kids
  stage: deploy
  script:
    - sudo mkdir -p /home/monas/www/kids.monas.lt/public/farm
    - sudo rsync -rav --delete --exclude='.git/' . /home/monas/www/kids.monas.lt/public/farm/$CI_COMMIT_BRANCH
  #artifacts:
  #  paths:
  #    - public
